// <auto-generated />
using System;
using Baitap1.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Baitap1.Migrations
{
    [DbContext(typeof(data_context))]
    [Migration("20231012081603_kt")]
    partial class kt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Baitap1.Models.CuaHang", b =>
                {
                    b.Property<int>("id_cuahang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_cuahang"));

                    b.Property<string>("TenCH")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_cuahang");

                    b.ToTable("CuaHangs");
                });

            modelBuilder.Entity("Baitap1.Models.NamThang", b =>
                {
                    b.Property<int>("id_namthang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_namthang"));

                    b.Property<DateTime>("NLHD")
                        .HasColumnType("datetime2");

                    b.HasKey("id_namthang");

                    b.ToTable("NamThangs");
                });

            modelBuilder.Entity("Baitap1.Models.NhanVien", b =>
                {
                    b.Property<int>("id_nhanvien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_nhanvien"));

                    b.Property<bool>("Admins")
                        .HasColumnType("bit");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gioitinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngaysinh")
                        .HasColumnType("datetime2");

                    b.HasKey("id_nhanvien");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("Baitap1.Models.PhanQuyen", b =>
                {
                    b.Property<int>("id_phanquyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_phanquyen"));

                    b.Property<int>("id_cuahang")
                        .HasColumnType("int");

                    b.Property<int>("id_namthang")
                        .HasColumnType("int");

                    b.Property<int>("id_nhanvien")
                        .HasColumnType("int");

                    b.Property<int>("id_sanpham")
                        .HasColumnType("int");

                    b.HasKey("id_phanquyen");

                    b.HasIndex("id_cuahang");

                    b.HasIndex("id_namthang");

                    b.HasIndex("id_nhanvien");

                    b.HasIndex("id_sanpham");

                    b.ToTable("PhanQuyens");
                });

            modelBuilder.Entity("Baitap1.Models.SanPham", b =>
                {
                    b.Property<int>("id_sanpham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_sanpham"));

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GiaBan")
                        .HasColumnType("int");

                    b.Property<string>("TenSP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_sanpham");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("Baitap1.Models.PhanQuyen", b =>
                {
                    b.HasOne("Baitap1.Models.CuaHang", "CuaHang")
                        .WithMany()
                        .HasForeignKey("id_cuahang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Baitap1.Models.NamThang", "NamThang")
                        .WithMany()
                        .HasForeignKey("id_namthang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Baitap1.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("id_nhanvien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Baitap1.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("id_sanpham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuaHang");

                    b.Navigation("NamThang");

                    b.Navigation("NhanVien");

                    b.Navigation("SanPham");
                });
#pragma warning restore 612, 618
        }
    }
}
